---
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  id-token: write

jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Yarn
        run: |
            corepack enable
            yarn set version stable
      - name: Install dependencies
        run: yarn install
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version
        run: python --version
      - name: Install Python dependencies
        run: python -m pip install --upgrade waldiez
      - name: Run tests on Linux
        run: |
          apt update && apt install -y xvfb libasound2 libgbm1 libgtk-3-0 libnss3
          xvfb-run -a yarn run test
        if: runner.os == 'Linux'
      - name: Run tests on Windows and MacOS
        run: yarn run test
        if: runner.os != 'Linux'
      - name: Create VSIX
        run: yarn run build
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v4
        with:
          name: waldiez-vscode-${{ github.ref_name }}.vsix
          path: waldiez-vscode-*.vsix
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      - name: Create Release
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          repository: ${{ github.repository }}
          files: |
            waldiez-vscode-*.vsix
      # - name: Publish
      #   if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      #   run: yarn run deploy
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
