---
name: Package
# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish_waldiez_vscode:
    runs-on: ubuntu-latest
    name: Publish VSCode 🌐 distribution 📦 to Marketplace

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install corepack and yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Install dependencies
        run: yarn install

      - name: Create VSIX
        id: create_vsix
        run: |
          yarn cache clean
          yarn install
          yarn run build

      - name: Publish to VSCode Marketplace
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: yarn run deploy

      - name: List file if dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          ls -la dist
